HG002_fully_resolved_path = 'HG002_fully_resolved/HG002_GRCh38_1_22_v4.2.1_benchmark_renamed.vcf.gz'
workflow_results_dir = 'workflow_results'
flat_results_dir = '.'
bedfiles_dir = 'bedfiles'
refs_dir = 'refs'