HG002_fully_resolved_path = 'HG002_fully_resolved/HG002_GRCh38_1_22_v4.2.1_benchmark_renamed.vcf.gz'
workflow_results_dir = '/data/scratch/xchen/sarek_pipeline_results'
flat_results_dir = '.'
bedfiles_dir = '/data/xchen/refs'
refs_dir = '/data/xchen/refs'
sample_prep_table_path = 'manuscript_sample_prep_table_20241211.csv'